baseurl = "https://www.sunlit.tk"
title = "Sunlit's Blog"
author = "@PengHui Yang"
canonifyurls = true
copyright = "Copyright © 2001–2019, @PengHui Yang"

summaryLength = 30
paginate = 5
theme = "jeffprod"

[permalinks]
  posts = "/:year/:title/"

[taxonomies]
    tag = "tags"
    archive = "archives"
